ting project:
  type: book

book:
  title: "Overleaf Starter Guide"
  author: "IQSS"
  date: "last-modified"
  page-navigation: true
  search: true
  favicon: images/favicon.png
  chapters:
    - index.qmd
    - introduction.qmd
    - part: "Getting Started with Overleaf"
      chapters:
        - step1.qmd
    - part: "Advanced Features & Tips"
      chapters:
        - step2.qmd
    - step3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
    code-link: true
    callout-appearance: simple

execute:
  freeze: auto

